apiVersion: v1
kind: Secret
metadata:
  name: rag-secrets
  namespace: financial-rag
type: Opaque
stringData:
  MINIO_ACCESS_KEY: "admin"
  MINIO_SECRET_KEY: "password123"
  HUGGINGFACE_TOKEN: ""   # ← optionnel